[package]
name = "cli"
version = "0.1.0"
authors = ["Kilerd <blove694@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avaro = { path = ".." }
serde_json = "1.0.64"
structopt = "0.3.23"
